config/routes.rb
Rails.application.routes.draw do
  devise_for :developers
  resources :teams do
    resource :project, except: :destroy do
      resource :gemfile, only: %i(show edit update) do
        resources :gem_suggestions, only: %i(index create destroy update)
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/developer.rb
class Developer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable and :timeoutable, :omniauthable,
  devise :confirmable, :database_authenticatable,
         :recoverable, :registerable, :rememberable, :trackable, :validatable
  enum role: { staff: 0, team_leader: 1, manager: 2 }
  has_many :teams, through: :developer_teams
  has_many :developer_teams
end

app/models/developer_team.rb
class DeveloperTeam < ApplicationRecord
  belongs_to :developer
  belongs_to :team
end

app/models/gem_suggestion.rb
class GemSuggestion < ApplicationRecord
  belongs_to :developer
  belongs_to :gemfile
end

app/models/gemfile.rb
class Gemfile < ApplicationRecord
  belongs_to :project
  has_many :developers, through: :gem_suggestions
  has_many :gem_suggestions
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :team
  has_one :gemfile
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :developers, through: :developer_teams
  has_many :developer_teams
  has_one :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gem_suggestions_controller.rb
class GemSuggestionsController < ApplicationController
  def index
    @suggestions = GemSuggestion.all
  end

end

app/controllers/gemfiles_controller.rb
class GemfilesController < ApplicationController
  def show
    @gemfile = Gemfile.find(params[:team_id])
  end

  def edit
    @gemfile = Gemfile.find(params[:team_id])
  end

  def update
    @gemfile = Gemfile.find(params[:team_id])
    @gemfile.update(gemfile_params)
    redirect_to team_project_gemfile_path
  end

  private

  def gemfile_params
    params.require(:gemfile).permit(:context)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Team.find(params[:team_id]).project
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i(show edit update)

  def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    @team.save(team_params)
    redirect_to teams_path
  end

  def show; end

  def edit; end

  def update
    @team.update(team_params)
    redirect_to teams_path
  end

  private

  def set_team
    @team = Team.find(params[:id])
  end

  def team_params
    params.require(:team).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  @@markdown = Redcarpet::Markdown.new Redcarpet::Render::HTML,
                                       autolink: true,
                                       space_after_headers: true,
                                       no_intra_emphasis: true,
                                       fenced_code_blocks: true,
                                       tables: true,
                                       hard_wrap: true,
                                       xhtml: true,
                                       lax_html_blocks: true,
                                       strikethrough: true

  def html(markdown)
    @@markdown.render(markdown).html_safe
  end
end

app/views/gem_suggestions/index.html.erb
<% @suggestions.each do |suggestion| %>
  <%= suggestion.sentence %>
  <%= suggestion.developer.name %>
  <br />
<% end %>

app/views/gemfiles/_form.html.erb
<%= form_for @gemfile, url: team_project_gemfile_path do |f| %>

  <% if @gemfile.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@gemfile.errors.count, "error") %> prohibited this gemfile from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @gemfile.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :context, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :context, :class => 'form-control', row: 50 %>

    </div>
    <%=f.error_span(:context) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/gemfiles/edit.html.erb
<%- model_class = Gemfile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/gemfiles/index.html.erb
<%- model_class = Gemfile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:context) %></th>
      <th><%= model_class.human_attribute_name(:project_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @gemfiles.each do |gemfile| %>
      <tr>
        <td><%= link_to gemfile.id, gemfile_path(gemfile) %></td>
        <td><%= gemfile.context %></td>
        <td><%= gemfile.project_id %></td>
        <td><%=l gemfile.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      gemfile_path(gemfile), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_gemfile_path(gemfile), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      gemfile_path(gemfile),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_gemfile_path,
            :class => 'btn btn-primary' %>

app/views/gemfiles/new.html.erb
<%- model_class = Gemfile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/gemfiles/show.html.erb
<%- model_class = Gemfile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div>
    <%= html @gemfile.context %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gemologist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => "form-horizontal project" } do |f| %>

  <% if @project.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :team_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :team_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:team_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:team_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.id, project_path(project) %></td>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.team_id %></td>
        <td><%=l project.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      project_path(project), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_project_path(project), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      project_path(project),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_path,
            :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @project.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @project.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:team_id) %>:</strong></dt>
  <dd><%= @project.team_id %></dd>
</dl>

<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_team_project_path(@project), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              team_project_path(@project),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>